# Generated by Django 5.0 on 2023-12-27 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_vacancy_photo'),
        ('users', '0004_alter_inmessages_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmessages',
            name='vacs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.vacancy'),
        ),
    ]
