# Generated by Django 5.0 on 2023-12-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_vacancy_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/vacancy_photos/'),
        ),
    ]
